### ISSUE TITLE
Running on colab

### ISSUE THREAD

**Issue by plaidam** [aim-uofa/AdelaiDepth#6]
```
loading checkpoint res50.pth
Traceback (most recent call last):
  File "./test_shape.py", line 96, in <module>
    load_ckpt(args, depth_model, shift_model, focal_model)
  File "/content/AdelaiDepth/LeReS/lib/net_tools.py", line 33, in load_ckpt
    checkpoint = torch.load(args.load_ckpt)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
loading checkpoint res101.pth
Traceback (most recent call last):
  File "./test_shape.py", line 96, in <module>
    load_ckpt(args, depth_model, shift_model, focal_model)
  File "/content/AdelaiDepth/LeReS/lib/net_tools.py", line 33, in load_ckpt
    checkpoint = torch.load(args.load_ckpt)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

I'm trying to convert this to colab and get this error message.
What version of torch are you using?

**Comment by YvanYin** [comment]
I am using pytorch-160, torchvision 0.7.0

**Comment by dvschultz** [comment]
This happens because ninja does not come pre-installed on colab. I recommend adding ninja to your requirements.txt file
